language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install -r test-requirements.txt

script:
  - bandit -r SHIMON
  - pytest
  - vulture SHIMON whitelist.py
  - vulture testing whitelist.py
  - "[[ $(mypy -p SHIMON | tail -n 1 | awk '{print $2}') -le 11 ]]"
  - "[[ $(mypy -p testing | tail -n 1 | awk '{print $2}') -le 13 ]]"